version: '3.9'
services:
  database:
    image: mongo:4.2
    restart: always
    container_name: six-sities-794021_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - six-cities-4-794021:/data/db

  database_web_panel:
    image: mongo-express
    restart: always
    container_name: six-sities-794021_mongo-express
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@database:27017/

volumes:
  six-cities-4-794021:
